# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10
  identifier = "home"
  
[[main]]
  name = "About"
  url = "#about"
  weight = 11 
  parent="home"
  
[[main]]
  name = "Education"
  url = "#experience"
  weight = 12 
  parent="home"

[[main]]
  name = "Publications"
  url = "#featured"
  weight = 15
  parent="home"


[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60
  parent="home"
  
[[main]]
  name = "Activities"  # Title of the link.
  url = "activities/"  # Widget Page folder name.
  weight = 16  # Position of the link in the navigation bar.
  identifier = "activities"

#[[main]]
#  name = "Other"  # Title of the link.
#  url = "other/"  # Widget Page folder name.
#  weight = 18  # Position of the link in the navigation bar.
#  identifier = "other"

#[[main]]
#  name = "Krino"  # Title of the link.
#  url = "other/#krino"  # Widget Page folder name.
#  weight = 1  # Position of the link in the navigation bar.
#  parent = "other"

#[[main]]
#  name = "Dissemination"  # Title of the link.
#  url = "other/#dissemination"  # Widget Page folder name.
#  weight = 2  # Position of the link in the navigation bar.
#  parent = "other"

#[[main]]
#  name = "Random thoughts"  # Title of the link.
#  url = "other/#random"  # Widget Page folder name.
#  weight = 3  # Position of the link in the navigation bar.
#  parent = "other"


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
